[package]
name = "oxc_sourcemap_binding"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2.99" }
oxc_sourcemap = { version = "1.0.4" }
base64 = "0.22.1"
